services:
  dev-server:
    container_name: dev-server-container
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    env_file: "./.env.development"
    ports:
      - "3000:3000" # port 3000 on host machine is mapped to port 3000 on container
    # When pc restarts it will start the server again, until I stop it with docker stop
    # restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules # This is perserved and not overwritten by command above
  server:
      container_name: server-container
      build:
        context: ./server
        dockerfile: Dockerfile
      # Define project env variables
      env_file: "./.env.production"
      # Uses container env variables, defined with --env-file when runing docker compose
      ports:
        - "8080:8080"
